### PR TITLE
final for file for publication

### PR DESCRIPTION
**Pull request by thiagochacon**
This file shoudl substitute "huber1992_complete_23-01-18", as the new file only has the 130 concepts which have been better curated and actually used in Chacon 2017

### CODE REVIEW

**Comment by LinguList** [comment]
you have to merge this now first!

**Comment by LinguList** [comment]
then, make a new pull request, but from your "master" to Lexibank, you only made an internal pull request the last time...

**Comment by thiagochacon** [comment]
did it work now?

**Comment by LinguList** [comment]
I just did it from your repo.

**Pull request merged**
